### ISSUE TITLE
SmartQuery error() handler gets called twice even though query was retrieved once from the network

### ISSUE THREAD

**Issue by fabis94** [vuejs/vue-apollo#1133] opened 2021-01-27 16:28 UTC
**Describe the bug**
For some reason error() handler of my query gets called twice, once as an Error and the 2nd time as a GraphQLError. The query results definitely aren't in a cache or anything, so why does this happen?

**To Reproduce**
Nothing special, the query is registered like this:

```javascript
apollo: {
        failingQuery: {
            query: failingQuery,
            error(err) {
                alert(err.message);
            }
        }
    },
```

And the alert is invoked twice.

**Expected behavior**
The handler should be called once, why would it be called twice?

**Versions**
vue: 2.6.11
@vue/apollo-option: 4.0.0-alpha.11 and also 3.x
apollo-client: 3.3.6

**Additional context**
No special setup is done here, it's a basic query that hasn't been cached

**Comment by fabis94** [comment] 2021-02-09 22:01
To me it looks like the issue is in smart-query.js, specifically the `catchError` method.

![image](https://user-images.githubusercontent.com/938316/107433842-965ac500-6b32-11eb-92d2-59b320866f5c.png)

Whenever an error arrives here, it gets reported with `super.catchError`, but then the process continues on and calls `this.nextResult`. Inside the definition of `this.nextResult()` however, the error is reported a 2nd time, except this time it gets wrapped in a generic `Error` making it lose a lot of information (why is this necessary?).

![image](https://user-images.githubusercontent.com/938316/107434055-de79e780-6b32-11eb-8e7d-b4287bc7aafc.png)

Seems like a bug to me, I don't see why the error reporting part in `this.nextResult()` even needs to be there. Is it in any way possible for `nextResult()` to be invoked without `catchError()` also being invoked? Only that would explain why error handling code is duplicated there.

**Comment by Narretz** [comment] 2021-02-24 19:00
Hi @fabis94 did you find a way to fix this issue? I'm also encountering this after I updated to "@apollo/client": "^3.3.11" from 2.x (and using vue-apollo 3.0.7) @Akryum do you have any thoughts on this? This just seems broken.

**Comment by fabis94** [comment] 2021-02-24 19:05
Nope, I'm considering creating a fork since this project doesn't seem to be actively maintained

**Comment by Narretz** [comment] 2021-02-24 19:19
That would be the nuclear option ... a big problem is also that there don't seem to be a lot of tests, and many changes are committed without automatic tests. That's a nightmare scenario for such a popular library, because you might break something without knowing it.

**Comment by Narretz** [comment] 2021-02-24 21:02
I can confirm that this block seems to be the problem:

https://github.com/vuejs/vue-apollo/blob/92a4a11e2627d39981f2c9ec1e46e1fc9e6dcb09/packages/vue-apollo/src/smart-query.js#L172-L184

Commenting it out solves the double error problem with errorPolicy `none`

This problem also affects  `errorPolicy: 'all'`, because *with* the above block, it'll call *both* error and result, while the docs and code comments state that only *result* should be called (with data and an errors array). `ignore` seems to work with or without

Since this doesn't happen with Apollo 2.x, there might be an internal change there that caused this. Would make it more difficult to remove this block.
Come to think about it, when I was on Apollo Client 2.x, I received the Errors prefixed with GraphQL from this function. So something might have changed that we now get the actual error.

**Comment by Narretz** [comment] 2021-04-14 09:22
@Akryum can you please take a look at this? This is a serious issue.

**Comment by fabis94** [comment] 2021-04-14 09:25
I ended up creating a fork that solves some of the most obvious issues I encountered, the double error reporting and inconsistent result reporting in the ApolloQuery component:

https://github.com/vuejs/vue-apollo/compare/v3...fabis94:patch-1 (this is for vue apollo 3.x)

If the author can comment on these and tell me what I should be doing differently, I can create a formal PR from this and fix these issues

**Comment by flavioleggio** [comment] 2021-09-28 14:04
Any news on this one? I ran in the same issue

**Comment by nicolas-anaxago** [comment] 2021-10-26 10:04
same here :(

**Comment by Akryum** [comment] 2021-11-28 17:42
> Commenting it out solves the double error problem with errorPolicy `none`

The code you are commenting is necessary to retrieve the errors if `errorPolicy` is set to `all`, as validated by this test:

![image](https://user-images.githubusercontent.com/2798204/143779334-471aef82-b4e0-45e0-a492-7001f69b6424.png)

After commenting the code:

![image](https://user-images.githubusercontent.com/2798204/143779358-b97a76ee-fbd0-4dba-80a4-20e383e39e3e.png)

The actual fix I came up with is to ignore the `errors` from the response if Apollo Client is handling the error already:

![image](https://user-images.githubusercontent.com/2798204/143779426-bd22f60f-2539-47ea-8a76-c3565e5e4591.png)

![image](https://user-images.githubusercontent.com/2798204/143779432-fb72a224-e457-45d8-ad13-8ae982e78d0e.png)

After updating the test:

![image](https://user-images.githubusercontent.com/2798204/143779455-0ad55f1e-9a6c-443c-b41b-672a92c00218.png)

> That would be the nuclear option ... a big problem is also that there don't seem to be a lot of tests, and many changes are committed without automatic tests. That's a nightmare scenario for such a popular library, because you might break something without knowing it.

Thanks for the "there are no tests" comment. BTW you can contribute and send PRs with more tests :wink:

**Closed** 2021-11-28 17:55 UTC

**Comment by Narretz** [comment] 2021-12-04 14:11
Hi @Akryum thanks for the fix. Is it possible to backport this to the v3 branch? Or is v4 around the corner?
