### ISSUE TITLE
[vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.

### ISSUE THREAD

**Issue by szvest** [vuejs/vue-apollo#1036] opened 2020-08-08 14:49 UTC
I am getting this error after updading apollo-composable to the latest version. 

_**[vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.**_

I am using VueCompositionAPI as a Nuxt plugin.

```
import Vue from "vue";
import VueCompositionApi from "@vue/composition-api";

Vue.use(VueCompositionApi);
```

**To Reproduce**
1 - Upgrade from `@vue/apollo-composable` v 4.0.0-alpha.8 to v 4.0.0-alpha.10.
2 - Run `npm run dev`
3 - Go the browser

**Versions**
nuxt: 2.13.3
@nuxtjs/apollo: 4.0.1-rc.1
@vue/composition-api: v1.0.0-beta.8

**Comment by IRlyDontKnow** [comment] 2020-08-09 11:10
I've got same issue, but with the quasar framework.

**Comment by dietergoetelen** [comment] 2020-08-10 07:58
@szvest I've had a similar issue with nuxt, what I did was the following:

1. Create a folder `/composition` with the following content
**index.ts**
```
import Vue from "vue";
import VueCompositionApi from "@vue/composition-api";

Vue.use(VueCompositionApi);

export * from "@vue/composition-api"
```

2. Change composition references from "@vue/composition-api" to "@/composition"

**Comment by MechJosh0** [comment] 2020-08-10 11:04
Possible duplicate of https://github.com/vuejs/vue-apollo/issues/1029

**Comment by szvest** [comment] 2020-08-10 14:15
Thanks, @dietergoetelen. These are the steps I followed:

1. Upgrade from @vue/apollo-composable v 4.0.0-alpha.8 to v 4.0.0-alpha.10. 

2. Remove the `composition-api` plugin from nuxt.config
 ```
 plugins: [ 
// { src: "@/plugins/composition-api" },
]
```
3. Create /composition folder and transfer composition-api.js from the plugin folder to the new folder with the following `export` added.
```
export * from "@vue/composition-api"
```
4. Find and replace all occurrences of `from "@vue/composition-api"` to `from "@/composition"`

Same issue. Nothing fixed.

**Comment by DarkLite1** [comment] 2020-08-24 13:43
> I've got same issue, but with the quasar framework.

Maybe my [answer](https://stackoverflow.com/questions/62830159/how-to-add-vue-apollo-composable-to-quasar-frramework) on StackOverflow might help you.

**Comment by Akryum** [comment] 2020-10-15 15:18
See https://github.com/antfu/vue-demi/issues/7

**Closed by Akryum** 2020-10-15 15:18 UTC
Labels: v4
