### ISSUE TITLE
Support partial-success messages in smart subscriptions: Don't stop subscription on first error?

### ISSUE THREAD

**Issue by sgrove** [vuejs/vue-apollo#1071] opened 2020-10-08 18:59 UTC
The `start`, `stop`, and `refresh` methods on the subscriptions object are *great*, I've been hoping for kind of API for awhile (I often know in my component when something has changed, like a user logging into a service, and it's time to refresh a subscription)!

## Goal 1: Don't automatically stop subscription on the first error
Along those lines however, I *don't* have control to say, "It's ok to receive an error in this subscription, I can handle it and continue the subscription". I'd love to have an option in the smart subscription similar to `error-policy: all`.

## Goal 2: Support partial success
To take this even further, I'd really like to be able to support partial success. Right now whenever I get a messages that has some data *and* some errors, I'd like to be able to run both of my handlers - again, I suspect this is similar to `error-policy: all`.

**Comment by Akryum** [comment] 2021-11-18 12:51
Duplicate of #877

**Closed by Akryum** 2021-11-18 12:51 UTC
Labels: enhancement
